name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project card To Do
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event_name == 'issues' && github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Finantele-Salbatice/projects/1'
        column_name: 'To Do'
    - name: Assign NEW pull-requests to project card In Progress
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Finantele-Salbatice/projects/1'
        column_name: 'In Progress'
